mod_name=CMDCam
mod_id=cmdcam
mod_authors=CreativeMD, BluSpring, rPersival
mod_description=Create camera paths.
mod_version=2.2.7-fabric
mod_display_url=https://modrinth.com/mod/cmdcam-fabric
release_type=release
github_project=BluSpring/CMDCam-Fabric
creativecore_version=2.13.0
curse_id=251244
mod_license=LGPL-3.0-only

org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false

minecraft_version=26.1.2
minecraft_version_range=~26.1

fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.1.2
resource_pack_format=34
data_pack_format=34
